### ISSUE TITLE
Expose Time.Distance.Types module

### ISSUE THREAD

**Issue by janslifka** [gingko/time-distance#1]
It is impossible to create a custom localization because `Time.Distance.Types` is not exposed. The custom localization function would need to do some pattern matching on the types defined in that module. However, it is not exposed from the library therefore it cannot be used anywhere else.

**Comment by AdrianoFerrari** [comment]
Hi Jan. I had a quick look, but I'm not sure what you mean. Am I missing something?

I'm able to use this package as is, here for example:
[gingko/client/src/elm/Translation.elm](https://github.com/gingko/client/blob/b384f49e0bcdb40ae06471b30524640cf3e25dbb/src/elm/Translation.elm#L413)

To add another custom language to the package, I would add it to this library following the pattern set out by the others.

Let me know if I've misunderstood.

**Comment by janslifka** [comment]
> To add another custom language to the package, I would add it to this library following the pattern set out by the others.

This is the problem for me. Because my application is loading localizations from a server and I simply want to pass my own custom function that can get the values from the loaded localization. There can be many different localization created that I am not aware of when building the application.

However, since the  `Time.Distance.Types` module cannot be imported, I cannot create such function. The workaround for me was to just copy the whole library into my codebase, which is of course not ideal.

**Comment by AdrianoFerrari** [comment]
@janslifka published version 2.1.0, with exposed `Time.Distance.Types`. Reopen if that doesn't help.

Thanks :relaxed:
